---
layout: single
title:  "Kotlin 기본 문법 (Try-Catch문)"
categories: kotlin
tag: Kotlin
toc: true
---

# Try-Catch문 

Try-Catch를 사용한 예외 처리에서 4개의 키워드가 있다 대표적으로 try, catch, finally, throw 로

## try

try 블록은 예외를 발생시킬 수 있는 구문 세트를 포함하며 try 뒤에는
catch나 finally, 아니면 둘 다 꼭 뒤에 따라와야 한다

## catch

catch 블록은 try 블록에서 던져진 예외를 잡는 부분으로
만약 try 블록에 예외가 있으면 catch 블록이 실행된다 

## finally

final 블록은 중요한 코드 구문을 실행하는 데 사용되는 블록으로 예외가 처리되든지 말든지 실행된다

## throw

throw는 오류를 일으키기 위해 입력하는 것으로
오류가 어디서 나는지 테스트할 때 매우 유용하다

코드
~~~
 try {
        val a = reader.readLine()
        return Integer.parseInt(a) 
    } catch (e: NumberFormatException) {
        return null 
    } finally {
        reader.close() 
    }
~~~